{% set version = "1.2.0" %}

package:
  name: bibparse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bibparse/bibparse-{{ version }}.tar.gz
  sha256: aaf891e6d523567bd8b2d3e12549b363492c34551bd4f10fc47620f041d034c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - bibparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/Legisign/bibparse
  summary: Read and write BibTeX files
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
